# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6.1

    working_directory: ~/repo

    steps:
      - checkout

      - run:
          name: Setup Env
          command: |
            echo 'export PATH=$PATH:/home/circleci/.local/bin' >> $BASH_ENV
            sudo chmod 777 -R /usr/local/bin

      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "pyproject.lock" }}

      - run:
          name: Install Dependencies
          command: |
            make bootstrap
            make install

      - save_cache:
          paths:
            - /home/circleci/.cache/pypoetry/virtualenvs/watchmelog-py3.6
          key: v1-dependencies-{{ checksum "pyproject.lock" }}

      - run:
          name: Lint
          command: |
            make lint

  deploy-dev:
      - checkout

      - run:
          name: Setup Env
          command: |
            echo 'export PATH=$PATH:/home/circleci/.local/bin' >> $BASH_ENV
            sudo chmod 777 -R /usr/local/bin

      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "pyproject.lock" }}

      - run:
          name: Install Dependencies
          command: |
            make bootstrap
            make install

      - save_cache:
          paths:
            - /home/circleci/.cache/pypoetry/virtualenvs/watchmelog-py3.6
          key: v1-dependencies-{{ checksum "pyproject.lock" }}

      - run:
          name: Deploy to Lambda
          command: |
            source /home/circleci/.cache/pypoetry/virtualenvs/watchmelog-py3.6/bin/activate
            zappa update dev

workflows:
  version: 2
  build-test-and-deploy:
    jobs:
      - build
      - deploy-dev:
          filters:
            branches:
              only:
                - master
          requires:
            - build
